package org.example.gui;

import java.util.*;

public class LocalizationManager {
    private static final Map<String, Map<String, String>> LOCALIZATION = new HashMap<>();
    private static final Map<String, Locale> SUPPORTED_LOCALES = new HashMap<>();

    static {
        initializeLocales();
        initializeLocalization();
    }

    private static void initializeLocales() {
        SUPPORTED_LOCALES.put("Русский", new Locale("ru", "RU"));
        SUPPORTED_LOCALES.put("Suomi (Финский)", new Locale("fi", "FI"));
        SUPPORTED_LOCALES.put("Shqip (Албанский)", new Locale("sq", "AL"));
        SUPPORTED_LOCALES.put("Español (Коста-Рика)", new Locale("es", "CR"));
    }

    private static void initializeLocalization() {
        // Русский
        Map<String, String> ru = new HashMap<>();
        ru.put("commands.title", "команды");
        ru.put("command.add", "Добавить");
        ru.put("command.clear", "Очистить");
        ru.put("command.executescript", "Выполнить скрипт");
        ru.put("command.groupcountingbylabel", "Группировка по лейблу");
        ru.put("command.execute_script", "Выполнить скрипт");
        ru.put("command.group_counting", "Группировка по лейблу");
        ru.put("command.help", "Помощь");
        ru.put("command.info", "Информация");
        ru.put("command.printdescending", "Печать по убыванию");
        ru.put("command.printfieldascending", "Печать лейблов по возрастанию");
        ru.put("command.removeat", "Удалить по индексу");
        ru.put("command.removefirst", "Удалить первый");
        ru.put("command.print_descending", "Печать по убыванию");
        ru.put("command.print_field_ascending", "Печать лейблов по возрастанию");
        ru.put("command.remove_at", "Удалить по индексу");
        ru.put("command.remove_first", "Удалить первый");
        ru.put("command.shuffle", "Перемешать");
        ru.put("command.updateid", "Обновить по ID");
        ru.put("command.update_id", "Обновить по ID");
        ru.put("title", "Z1rotaLab8");
        ru.put("login.title", "Вход");
        ru.put("register.title", "Регистрация");
        ru.put("mainmenu.title", "Главное меню");
        ru.put("login.username", "Логин:");
        ru.put("login.password", "Пароль:");
        ru.put("login.button", "Войти");
        ru.put("login.no_account", "У меня нет аккаунта");
        ru.put("login.error", "Неверный логин или пароль");
        ru.put("login.connection_error", "Ошибка подключения");
        ru.put("login.input_error", "Ошибка ввода данных");
        ru.put("register.login.label", "Логин:");
        ru.put("register.password.label", "Пароль:");
        ru.put("register.confirm.label", "Подтвердите:");
        ru.put("register.button", "Зарегистрироваться");
        ru.put("register.back.link", "У меня есть аккаунт");
        ru.put("register.passwords_mismatch", "Ошибка: пароли не совпадают!");
        ru.put("register.empty_password", "Ошибка: Введите пароль!");
        ru.put("register.error", "Ошибка регистрации:");
        ru.put("register.connection_error", "Ошибка подключения");
        ru.put("mainmenu.user", "Пользователь: ");
        ru.put("mainmenu.unknown_user", "неизвестен");
        ru.put("mainmenu.table_btn", "Таблица");
        ru.put("mainmenu.graph_btn", "График");
        ru.put("table.filter_label", "Фильтр по:");
        ru.put("table.button.add", "+ Добавить");
        ru.put("table.button.remove", "- Удалить");
        ru.put("table.column.id", "ID");
        ru.put("table.column.name", "Название");
        ru.put("table.column.x", "X");
        ru.put("table.column.y", "Y");
        ru.put("table.column.participants", "Участники");
        ru.put("table.column.date", "Дата основания");
        ru.put("table.column.genre", "Жанр");
        ru.put("table.column.label", "Лейбл");
        ru.put("table.column.label_bands", "Групп на лейбле");
        ru.put("table.column.sales", "Продажи");
        ru.put("table.error.date_format", "Неверный формат даты. Используйте yyyy-MM-ddTHH:mm:ss");
        ru.put("table.error.update", "Ошибка обновления: ");
        ru.put("graph.x_axis", "X");
        ru.put("graph.y_axis", "Y");
        ru.put("success.update", "Обновление выполнено успешно");
        ru.put("dialog.response.title","ඩඩඩඩඩඩඩඩඩඩඩඩ");
        ru.put("dialog.band_info.id", "ID");
        ru.put("dialog.band_info.name", "Название");
        ru.put("dialog.band_info.x", "X");
        ru.put("dialog.band_info.y", "Y");
        ru.put("dialog.band_info.participants", "Количество участников");
        ru.put("dialog.band_info.date", "Дата создания");
        ru.put("dialog.band_info.genre", "Жанр");
        ru.put("dialog.band_info.label", "Лейбл");
        ru.put("dialog.band_info.label_bands", "Группы на лейбле");
        ru.put("dialog.band_info.label_sales", "Продажи лейбла");
        ru.put("dialog.band_info.owner", "Владелец");
        ru.put("dialog.add.name", "Имя");
        ru.put("dialog.add.x", "X");
        ru.put("dialog.add.y", "Y");
        ru.put("dialog.add.participants", "Количество участников");
        ru.put("dialog.add.date", "Дата создания");
        ru.put("dialog.add.genre", "Жанр");
        ru.put("dialog.add.label", "Лейбл");
        ru.put("dialog.add.label_bands", "Группы на лейбле");
        ru.put("dialog.add.label_sales", "Продажи лейбла");
        ru.put("button.add","Добавить");
        ru.put("button.cancel", "Отмена");
        ru.put("dialog.add.title", "ඩඩඩඩඩඩඩඩඩඩඩඩ");
        ru.put("button.close", "Закрыть");
        ru.put("dialog.band_info.title", "ඩඩඩඩඩඩඩඩඩඩඩඩ");
        ru.put("button.close","Закрыть");
        ru.put("dialog.band_info.title","ඩඩඩඩඩඩඩඩඩඩඩඩ");
        ru.put("dialog.add.title","ඩඩඩඩඩඩඩඩඩඩඩඩ");
        LOCALIZATION.put("ru", ru);

        // Финский
        Map<String, String> fi = new HashMap<>();
        fi.put("commands.title", "Komennot");
        fi.put("command.add", "Lisää");
        fi.put("command.clear", "Tyhjennä");
        fi.put("command.executescript", "Suorita komentosarja");
        fi.put("command.groupcountingbylabel", "Ryhmittely levy-yhtiön mukaan");
        fi.put("command.help", "Ohje");
        fi.put("command.info", "Tiedot");
        fi.put("command.printdescending", "Tulosta laskevassa järjestyksessä");
        fi.put("command.printfieldascending", "Tulosta levy-yhtiöt nousevassa järjestyksessä");
        fi.put("command.removeat", "Poista indeksin mukaan");
        fi.put("command.removefirst", "Poista ensimmäinen");
        fi.put("command.shuffle", "Sekoita");
        fi.put("command.updateid", "Päivitä ID:n mukaan");
        fi.put("title", "ඩඩඩඩඩඩඩඩඩඩඩඩ");
        fi.put("login.title", "Kirjautuminen");
        fi.put("register.title", "Rekisteröinti");
        fi.put("mainmenu.title", "Päävalikko");
        fi.put("login.username", "Käyttäjätunnus:");
        fi.put("login.password", "Salasana:");
        fi.put("login.button", "Kirjaudu");
        fi.put("login.no_account", "Minulla ei ole tiliä");
        fi.put("login.error", "Väärä käyttäjätunnus tai salasana");
        fi.put("login.connection_error", "Yhteysvirhe");
        fi.put("login.input_error", "Syötteen käsittelyvirhe");
        fi.put("register.login.label", "Käyttäjätunnus:");
        fi.put("register.password.label", "Salasana:");
        fi.put("register.confirm.label", "Vahvista salasana:");
        fi.put("register.button", "Rekisteröidy");
        fi.put("register.back.link", "Minulla on jo tili");
        fi.put("register.passwords_mismatch", "Virhe: salasanat eivät täsmää!");
        fi.put("register.empty_password", "Virhe: Anna salasana!");
        fi.put("register.error", "Rekisteröintivirhe:");
        fi.put("register.connection_error", "Yhteysvirhe");
        fi.put("mainmenu.user", "Käyttäjä: ");
        fi.put("mainmenu.unknown_user", "tuntematon");
        fi.put("mainmenu.table_btn", "Taulukko");
        fi.put("mainmenu.graph_btn", "Kaavio");
        fi.put("table.filter_label", "Suodata:");
        fi.put("table.button.add", "+ Lisää");
        fi.put("table.button.remove", "- Poista");
        fi.put("table.column.id", "ID");
        fi.put("table.column.name", "Nimi");
        fi.put("table.column.x", "X");
        fi.put("table.column.y", "Y");
        fi.put("table.column.participants", "Jäsenet");
        fi.put("table.column.date", "Perustettu");
        fi.put("table.column.genre", "Tyylilaji");
        fi.put("table.column.label", "Levy-yhtiö");
        fi.put("table.column.label_bands", "Yhtyeitä");
        fi.put("table.column.sales", "Myynti");
        fi.put("table.error.date_format", "Virheellinen päivämäärämuoto. Käytä yyyy-MM-ddTHH:mm:ss");
        fi.put("table.error.update", "Päivitysvirhe: ");
        fi.put("graph.x_axis", "X");
        fi.put("graph.y_axis", "Y");
        fi.put("success.update", "Päivitys onnistui");
        fi.put("dialog.response.title","ඩඩඩඩඩඩඩඩඩඩඩඩ");
        fi.put("dialog.band_info.id", "ID");
        fi.put("dialog.band_info.name", "Nimi");
        fi.put("dialog.band_info.x", "X");
        fi.put("dialog.band_info.y", "Y");
        fi.put("dialog.band_info.participants", "Jäsenten määrä");
        fi.put("dialog.band_info.date", "Luomispäivä");
        fi.put("dialog.band_info.genre distingu", "Tyylilaji");
        fi.put("dialog.band_info.label", "Levy-yhtiö");
        fi.put("dialog.band_info.label_bands", "Yhtyeet levy-yhtiössä");
        fi.put("dialog.band_info.label_sales", "Levy-yhtiön myynti");
        fi.put("dialog.band_info.owner", "Omistaja");
        fi.put("dialog.band_info.title","ඩඩඩඩඩඩඩඩඩඩඩඩ");
        fi.put("button.close","Sulje");
        fi.put("dialog.add.name", "Nimi");
        fi.put("dialog.add.x", "X");
        fi.put("dialog.add.y", "Y");
        fi.put("dialog.add.participants", "Jäsenten määrä");
        fi.put("dialog.add.date", "Luomispäivä");
        fi.put("dialog.add.genre", "Tyylilaji");
        fi.put("dialog.add.label", "Levy-yhtiö");
        fi.put("dialog.add.label_bands", "Yhtyeet levy-yhtiössä");
        fi.put("dialog.add.label_sales", "Levy-yhtiön myynti");
        fi.put("button.add", "Lisää");
        fi.put("button.cancel", "Peruuta");
        fi.put("dialog.add.title", "ඩඩඩඩඩඩඩඩඩඩඩඩ");
        LOCALIZATION.put("fi", fi);

        // Албанский
        Map<String, String> sq = new HashMap<>();
        sq.put("commands.title", "Komandat");
        sq.put("command.add", "Shto");
        sq.put("command.clear", "Pastro");
        sq.put("command.executescript", "Ekzekuto skriptin");
        sq.put("command.groupcountingbylabel", "Grupim sipas etiketës");
        sq.put("command.help", "Ndihmë");
        sq.put("command.info", "Informacion");
        sq.put("command.printdescending", "Shfaq në rend zbritës");
        sq.put("command.printfielascending", "Shfaq etiketat në rend ngjitës");
        sq.put("command.removeat", "Fshi sipas indeksit");
        sq.put("command.removefirst", "Fshi të parin");
        sq.put("command.shuffle", "Përzie");
        sq.put("command.updateid", "Përditëso sipas ID");
        sq.put("title", "Z1rotaLab8");
        sq.put("login.title", "Hyrje");
        sq.put("register.title", "Regjistrimi");
        sq.put("mainmenu.title", "Menyja kryesore");
        sq.put("login.username", "Përdoruesi:");
        sq.put("login.password", "Fjalëkalimi:");
        sq.put("login.button", "Hyr");
        sq.put("login.no_account", "Nuk kam llogari");
        sq.put("login.error", "Përdoruesi ose fjalëkalim i gabuar");
        sq.put("login.connection_error", "Gabim në lidhje");
        sq.put("login.input_error", "Gabim në të dhëna");
        sq.put("register.login.label", "Përdoruesi:");
        sq.put("register.password.label", "Fjalëkalimi:");
        sq.put("register.confirm.label", "Konfirmo fjalëkalimin:");
        sq.put("register.button", "Regjistrohu");
        sq.put("register.back.link", "Kam një llogari");
        sq.put("register.passwords_mismatch", "Gabim: fjalëkalimet nuk përputhen!");
        sq.put("register.empty_password", "Gabim: Vendosni fjalëkalimin!");
        sq.put("register.error", "Gabim në regjistrim:");
        sq.put("register.connection_error", "Gabim në lidhje");
        sq.put("mainmenu.user", "Përdoruesi: ");
        sq.put("mainmenu.unknown_user", "i panjohur");
        sq.put("mainmenu.table_btn", "Tabela");
        sq.put("mainmenu.graph_btn", "Grafiku");
        sq.put("table.filter_label", "Filtro sipas:");
        sq.put("table.button.add", "+ Shto");
        sq.put("table.button.remove", "- Fshi");
        sq.put("table.column.id", "ID");
        sq.put("table.column.name", "Emri");
        sq.put("table.column.x", "X");
        sq.put("table.column.y", "Y");
        sq.put("table.column.participants", "Pjesëmarrësit");
        sq.put("table.column.date", "Data e themelimit");
        sq.put("table.column.genre", "Zhanri");
        sq.put("table.column.label", "Label");
        sq.put("table.column.label_bands", "Grupe në label");
        sq.put("table.column.sales", "Shitjet");
        sq.put("table.error.date_format", "Format i gabuar i datës. Përdorni yyyy-MM-ddTHH:mm:ss");
        sq.put("table.error.update", "Gabim në përditësim: ");
        sq.put("graph.x_axis", "X");
        sq.put("graph.y_axis", "Y");
        sq.put("success.update", "Përditësimi u krye me sukses");
        sq.put("dialog.response.title","ඩඩඩඩඩඩඩඩඩඩඩඩ");
        sq.put("dialog.band_info.id", "ID");
        sq.put("dialog.band_info.name", "Emri");
        sq.put("dialog.band_info.x", "X");
        sq.put("dialog.band_info.y", "Y");
        sq.put("dialog.band_info.participants", "Numri i pjesëmarrësve");
        sq.put("dialog.band_info.date", "Data e krijimit");
        sq.put("dialog.band_info.genre", "Zhanri");
        sq.put("dialog.band_info.label", "Etiketa");
        sq.put("dialog.band_info.label_bands", "Grupet në etiketë");
        sq.put("dialog.band_info.label_sales", "Shitjet e etiketës");
        sq.put("dialog.band_info.owner", "Pronari");
        sq.put("dialog.band_info.title","ඩඩඩඩඩඩඩඩඩඩඩඩ");
        sq.put("button.close","Mbyll");
        sq.put("dialog.add.name", "Emri");
        sq.put("dialog.add.x", "X");
        sq.put("dialog.add.y", "Y");
        sq.put("dialog.add.participants", "Numri i pjesëmarrësve");
        sq.put("dialog.add.date", "Data e krijimit");
        sq.put("dialog.add.genre", "Zhanri");
        sq.put("dialog.add.label", "Etiketa");
        sq.put("dialog.add.label_bands", "Grupet në etiketë");
        sq.put("dialog.add.label_sales", "Shitjet e etiketës");
        sq.put("button.add", "Shto");
        sq.put("button.cancel", "Anulo");
        sq.put("dialog.add.title", "ඩඩඩඩඩඩඩඩඩඩඩඩ");
        LOCALIZATION.put("sq", sq);

        // Испанский (Коста-Рика)
        Map<String, String> es = new HashMap<>();
        es.put("commands.title", "Comandos");
        es.put("command.add", "Añadir");
        es.put("command.clear", "Limpiar");
        es.put("command.executescript", "Ejecutar script");
        es.put("command.groupcounting", "Agrupación por etiqueta");
        es.put("command.help", "Ayuda");
        es.put("command.info", "Información");
        es.put("command.printdescending", "Mostrar en orden descendente");
        es.put("command.printfieldascending", "Mostrar etiquetas en orden ascendente");
        es.put("command.removeat", "Eliminar por índice");
        es.put("command.removefirst", "Eliminar primero");
        es.put("command.shuffle", "Mezclar");
        es.put("command.updateid", "Actualizar por ID");
        es.put("title", "Z1rotaLab8");
        es.put("login.title", "Iniciar sesión");
        es.put("register.title", "Registro");
        es.put("mainmenu.title", "Menú principal");
        es.put("login.username", "Usuario:");
        es.put("login.password", "Contraseña:");
        es.put("login.button", "Ingresar");
        es.put("login.no_account", "No tengo una cuenta");
        es.put("login.error", "Usuario o contraseña incorrectos");
        es.put("login.connection_error", "Error de conexión");
        es.put("login.input_error", "Error en los datos");
        es.put("register.login.label", "Usuario:");
        es.put("register.password.label", "Contraseña:");
        es.put("register.confirm.label", "Confirmar:");
        es.put("register.button", "Registrarse");
        es.put("register.back.link", "Ya tengo una cuenta");
        es.put("register.passwords_mismatch", "¡Error: las contraseñas no coinciden!");
        es.put("register.empty_password", "¡Error: Ingrese una contraseña!");
        es.put("register.error", "Error de registro:");
        es.put("register.connection_error", "Error de conexión");
        es.put("mainmenu.user", "Usuario: ");
        es.put("mainmenu.unknown_user", "desconocido");
        es.put("mainmenu.table_btn", "Tabla");
        es.put("mainmenu.graph_btn", "Gráfico");
        es.put("table.filter_label", "Filtrar por:");
        es.put("table.button.add", "+ Agregar");
        es.put("table.button.remove", "- Eliminar");
        es.put("table.column.id", "ID");
        es.put("table.column.name", "Nombre");
        es.put("table.column.x", "X");
        es.put("table.column.y", "Y");
        es.put("table.column.participants", "Participantes");
        es.put("table.column.date", "Fecha de fundación");
        es.put("table.column.genre", "Género");
        es.put("table.column.label", "Discográfica");
        es.put("table.column.label_bands", "Grupos en discográfica");
        es.put("table.column.sales", "Ventas");
        es.put("table.error.date_format", "Formato de fecha incorrecto. Use yyyy-MM-ddTHH:mm:ss");
        es.put("table.error.update", "Error de actualización: ");
        es.put("graph.x_axis", "X");
        es.put("graph.y_axis", "Y");
        es.put("success.update", "Actualización exitosa");
        es.put("dialog.response.title","ඩඩඩඩඩඩඩඩඩඩඩඩ");
        es.put("dialog.band_info.id", "ID");
        es.put("dialog.band_info.name", "Nombre");
        es.put("dialog.band_info.x", "X");
        es.put("dialog.band_info.y", "Y");
        es.put("dialog.band_info.participants", "Número de participantes");
        es.put("dialog.band_info.date", "Fecha de creación");
        es.put("dialog.band_info.genre", "Género");
        es.put("dialog.band_info.label", "Discográfica");
        es.put("dialog.band_info.label_bands", "Bandas en la discográfica");
        es.put("dialog.band_info.label_sales", "Ventas de la discográfica");
        es.put("dialog.band_info.owner", "Propietario");
        es.put("dialog.band_info.title","ඩඩඩඩඩඩඩඩඩඩඩඩ");
        es.put("button.close","Cerrar");
        es.put("dialog.add.name", "Nombre");
        es.put("dialog.add.x", "X");
        es.put("dialog.add.y", "Y");
        es.put("dialog.add.participants", "Número de participantes");
        es.put("dialog.add.date", "Fecha de creación");
        es.put("dialog.add.genre", "Género");
        es.put("dialog.add.label", "Discográfica");
        es.put("dialog.add.label_bands", "Bandas en la discográfica");
        es.put("dialog.add.label_sales", "Ventas de la discográfica");
        es.put("button.add", "Añadir");
        es.put("button.cancel", "Cancelar");
        es.put("dialog.add.title", "ඩඩඩඩඩඩඩඩඩඩඩඩ");
        LOCALIZATION.put("es", es);
    }

    public static Locale getLocale(String name) {
        return SUPPORTED_LOCALES.get(name);
    }

    public static String[] getSupportedLanguages() {
        return SUPPORTED_LOCALES.keySet().toArray(new String[0]);
    }

    public static String getLocalizedString(Locale locale, String key) {
        String lang = locale.getLanguage();
        Map<String, String> translations = LOCALIZATION.get(lang);
        return translations != null ? translations.getOrDefault(key, key) : key;
    }
}